<?php
// if(function_exists("register_field_group"))
// {
//   register_field_group(array (
//     'id' => 'acf_flexible-content-fields',
//     'title' => 'Flexible Content Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53b5b63132e87',
//         'label' => 'Flexible Content',
//         'name' => 'flexible_content',
//         'type' => 'flexible_content',
//         'layouts' => array (
//           array (
//             'label' => 'Text Block',
//             'name' => 'text_block',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53b5b75032e92',
//                 'label' => 'Content',
//                 'name' => 'content',
//                 'type' => 'wysiwyg',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'toolbar' => 'full',
//                 'media_upload' => 'yes',
//               ),
//             ),
//           ),
//           array (
//             'label' => 'Large Font Block',
//             'name' => 'large_font_block',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53b5b64b32e88',
//                 'label' => 'Content',
//                 'name' => 'content',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53e00dff571c3',
//                 'label' => 'Add a link to the end?',
//                 'name' => 'add_a_link_to_the_end',
//                 'type' => 'checkbox',
//                 'column_width' => '',
//                 'choices' => array (
//                   'Yes' => 'Yes',
//                 ),
//                 'default_value' => '',
//                 'layout' => 'vertical',
//               ),
//               array (
//                 'key' => 'field_53e00dcc571c1',
//                 'label' => 'Link Text',
//                 'name' => 'link_text',
//                 'type' => 'text',
//                 'conditional_logic' => array (
//                   'status' => 1,
//                   'rules' => array (
//                     array (
//                       'field' => 'field_53e00dff571c3',
//                       'operator' => '==',
//                       'value' => 'Yes',
//                     ),
//                   ),
//                   'allorany' => 'all',
//                 ),
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53e00dd8571c2',
//                 'label' => 'Link Destination',
//                 'name' => 'link_destination',
//                 'type' => 'text',
//                 'conditional_logic' => array (
//                   'status' => 1,
//                   'rules' => array (
//                     array (
//                       'field' => 'field_53e00dff571c3',
//                       'operator' => '==',
//                       'value' => 'Yes',
//                     ),
//                   ),
//                   'allorany' => 'all',
//                 ),
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//             ),
//           ),
//           array (
//             'label' => 'Three Columns Block',
//             'name' => 'three_columns_block',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53b5b67332e8a',
//                 'label' => 'Header for all three',
//                 'name' => 'header_for_all_three',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53b5b68132e8b',
//                 'label' => 'Columns',
//                 'name' => 'columns',
//                 'type' => 'repeater',
//                 'column_width' => '',
//                 'sub_fields' => array (
//                   array (
//                     'key' => 'field_53b5b69432e8c',
//                     'label' => 'Heading',
//                     'name' => 'heading',
//                     'type' => 'text',
//                     'column_width' => '',
//                     'default_value' => '',
//                     'placeholder' => '',
//                     'prepend' => '',
//                     'append' => '',
//                     'formatting' => 'html',
//                     'maxlength' => '',
//                   ),
//                   array (
//                     'key' => 'field_53b5b69c32e8d',
//                     'label' => 'Content',
//                     'name' => 'content',
//                     'type' => 'wysiwyg',
//                     'column_width' => '',
//                     'default_value' => '',
//                     'toolbar' => 'full',
//                     'media_upload' => 'yes',
//                   ),
//                   array (
//                     'key' => 'field_53b5b6ab32e8e',
//                     'label' => 'CTA Text',
//                     'name' => 'cta_text',
//                     'type' => 'text',
//                     'column_width' => '',
//                     'default_value' => '',
//                     'placeholder' => '',
//                     'prepend' => '',
//                     'append' => '',
//                     'formatting' => 'html',
//                     'maxlength' => '',
//                   ),
//                   array (
//                     'key' => 'field_53b5b6b732e8f',
//                     'label' => 'CTA Destination',
//                     'name' => 'cta_destination',
//                     'type' => 'page_link',
//                     'column_width' => '',
//                     'post_type' => array (
//                       0 => 'all',
//                     ),
//                     'allow_null' => 0,
//                     'multiple' => 0,
//                   ),
//                 ),
//                 'row_min' => 3,
//                 'row_limit' => 3,
//                 'layout' => 'row',
//                 'button_label' => 'Add Column',
//               ),
//               array (
//                 'key' => 'field_53b5b6e232e90',
//                 'label' => 'CTA below all three',
//                 'name' => 'cta_below_all_three',
//                 'type' => 'wysiwyg',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'toolbar' => 'full',
//                 'media_upload' => 'yes',
//               ),
//             ),
//           ),
//           array (
//             'label' => 'Quote',
//             'name' => 'quote',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53dfc5166a5b0',
//                 'label' => 'Image',
//                 'name' => 'image',
//                 'type' => 'image',
//                 'column_width' => '',
//                 'save_format' => 'object',
//                 'preview_size' => 'thumbnail',
//                 'library' => 'all',
//               ),
//               array (
//                 'key' => 'field_53dfc5166a5b1',
//                 'label' => 'Text Content',
//                 'name' => 'text_content',
//                 'type' => 'wysiwyg',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'toolbar' => 'full',
//                 'media_upload' => 'yes',
//               ),
//               array (
//                 'key' => 'field_53dfc5166a5b2',
//                 'label' => 'Attribution',
//                 'name' => 'attribution',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53dfc5166a5b3',
//                 'label' => 'CTA Text',
//                 'name' => 'cta_text',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53dfc5166a5b4',
//                 'label' => 'CTA Destination',
//                 'name' => 'cta_destination',
//                 'type' => 'page_link',
//                 'column_width' => '',
//                 'post_type' => array (
//                   0 => 'all',
//                 ),
//                 'allow_null' => 0,
//                 'multiple' => 0,
//               ),
//               array (
//                 'key' => 'field_53dfc5166a5b5',
//                 'label' => 'Background',
//                 'name' => 'background',
//                 'type' => 'radio',
//                 'column_width' => '',
//                 'choices' => array (
//                   'dark' => 'Dark',
//                   'light' => 'Light',
//                 ),
//                 'other_choice' => 0,
//                 'save_other_choice' => 0,
//                 'default_value' => 'light',
//                 'layout' => 'horizontal',
//               ),
//             ),
//           ),
//           array (
//             'label' => 'Featured Content',
//             'name' => 'featured_content',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53b5b77132e94',
//                 'label' => 'Image',
//                 'name' => 'image',
//                 'type' => 'image',
//                 'column_width' => '',
//                 'save_format' => 'object',
//                 'preview_size' => 'thumbnail',
//                 'library' => 'all',
//               ),
//               array (
//                 'key' => 'field_53b5b77d32e95',
//                 'label' => 'Text Content',
//                 'name' => 'text_content',
//                 'type' => 'wysiwyg',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'toolbar' => 'full',
//                 'media_upload' => 'yes',
//               ),
//             ),
//           ),
//           array (
//             'label' => 'Team Member',
//             'name' => 'team_member',
//             'display' => 'row',
//             'min' => '',
//             'max' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_548ddf22bad6f',
//                 'label' => 'Headshot',
//                 'name' => 'headshot',
//                 'type' => 'image_crop',
//                 'column_width' => '',
//                 'crop_type' => 'hard',
//                 'target_size' => 'custom',
//                 'width' => 280,
//                 'height' => 280,
//                 'preview_size' => 'thumbnail',
//                 'force_crop' => 'no',
//                 'save_in_media_library' => 'yes',
//                 'retina_mode' => 'no',
//                 'save_format' => 'object',
//               ),
//               array (
//                 'key' => 'field_53dfc6ec38676',
//                 'label' => 'Name',
//                 'name' => 'name',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53dfc6f638677',
//                 'label' => 'Title',
//                 'name' => 'title',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53dfc56fc883c',
//                 'label' => 'Text Content',
//                 'name' => 'text_content',
//                 'type' => 'wysiwyg',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'toolbar' => 'full',
//                 'media_upload' => 'yes',
//               ),
//               array (
//                 'key' => 'field_53dfc56fc883e',
//                 'label' => 'CTA Text',
//                 'name' => 'cta_text',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//               array (
//                 'key' => 'field_53dfc56fc883f',
//                 'label' => 'CTA Destination',
//                 'name' => 'cta_destination',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//             ),
//           ),
//         ),
//         'button_label' => 'Add Block',
//         'min' => '',
//         'max' => '',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'default',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//         0 => 'permalink',
//         1 => 'the_content',
//         2 => 'excerpt',
//         3 => 'custom_fields',
//         4 => 'discussion',
//         5 => 'comments',
//         6 => 'revisions',
//         7 => 'slug',
//         8 => 'author',
//         9 => 'format',
//         10 => 'featured_image',
//         11 => 'categories',
//         12 => 'tags',
//         13 => 'send-trackbacks',
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_happiness-test-confirmation-fields',
//     'title' => 'Happiness Test Confirmation Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53e108302d992',
//         'label' => 'Available Fields List',
//         'name' => '',
//         'type' => 'message',
//         'message' => 'Use the following shortcodes to insert test results:

//   [average_score]
//   [general_score]
//   [peer_score]
//   [generally_happy_score]
//   [generally_not_happy_score]
//   [email_address_submitted]
//   [email_results]
//   [email_signup]
//   [from_email]',
//       ),
//       array (
//         'key' => 'field_53e10f2f2d994',
//         'label' => 'Confirmation Page',
//         'name' => 'confirmation_page',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_53e12616b7fb2',
//         'label' => 'Confirmation Email Subject Line',
//         'name' => 'confirmation_email_subject_line',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_53e122c219d1a',
//         'label' => 'Confirmation Email From Address',
//         'name' => 'confirmation_email_from_address',
//         'type' => 'email',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//       ),
//       array (
//         'key' => 'field_53e10f242d993',
//         'label' => 'Confirmation Email',
//         'name' => 'confirmation_email',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'tpl-happiness_test_confirmation.php',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//         0 => 'permalink',
//         1 => 'the_content',
//         2 => 'excerpt',
//         3 => 'custom_fields',
//         4 => 'discussion',
//         5 => 'comments',
//         6 => 'revisions',
//         7 => 'slug',
//         8 => 'author',
//         9 => 'format',
//         10 => 'featured_image',
//         11 => 'categories',
//         12 => 'tags',
//         13 => 'send-trackbacks',
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_happy-clients-page-fields',
//     'title' => 'Happy Clients Page Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_54472b0b8ca13',
//         'label' => 'Client Quotes',
//         'name' => 'client_quotes',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_54472b1c8ca15',
//             'label' => 'Quote',
//             'name' => 'quote',
//             'type' => 'wysiwyg',
//             'column_width' => '',
//             'default_value' => '',
//             'toolbar' => 'full',
//             'media_upload' => 'yes',
//           ),
//           array (
//             'key' => 'field_54472f117376e',
//             'label' => 'Categories',
//             'name' => 'categories',
//             'type' => 'repeater',
//             'column_width' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_54472f1a7376f',
//                 'label' => 'Category',
//                 'name' => 'category',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//             ),
//             'row_min' => '',
//             'row_limit' => '',
//             'layout' => 'table',
//             'button_label' => 'Add Category',
//           ),
//         ),
//         'row_min' => '',
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Quote',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page',
//           'operator' => '==',
//           'value' => '36',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_home-page-fields',
//     'title' => 'Home Page Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53989c95610aa',
//         'label' => 'Home Page Slider',
//         'name' => 'home_page_slider',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_53989cb7610ab',
//             'label' => 'Image',
//             'name' => 'image',
//             'type' => 'image',
//             'column_width' => '',
//             'save_format' => 'object',
//             'preview_size' => 'thumbnail',
//             'library' => 'all',
//           ),
//           array (
//             'key' => 'field_541f0a7be7315',
//             'label' => 'Link Destination',
//             'name' => 'link_destination',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53989cdd610ac',
//             'label' => 'Title',
//             'name' => 'title',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53989d8f610ae',
//             'label' => 'Title Color',
//             'name' => 'title_color',
//             'type' => 'radio',
//             'column_width' => '',
//             'choices' => array (
//               'White' => 'white',
//               'Black' => 'black',
//               'Yellow' => 'yellow',
//             ),
//             'other_choice' => 0,
//             'save_other_choice' => 0,
//             'default_value' => 'Black : black',
//             'layout' => 'horizontal',
//           ),
//           array (
//             'key' => 'field_53989cf9610ad',
//             'label' => 'Call to Action',
//             'name' => 'call_to_action',
//             'type' => 'wysiwyg',
//             'column_width' => '',
//             'default_value' => '',
//             'toolbar' => 'full',
//             'media_upload' => 'yes',
//           ),
//           array (
//             'key' => 'field_53989db2610af',
//             'label' => 'Call to Action Color',
//             'name' => 'call_to_action_color',
//             'type' => 'radio',
//             'column_width' => '',
//             'choices' => array (
//               'White' => 'white',
//               'Black' => 'black',
//               'Yellow' => 'yellow',
//             ),
//             'other_choice' => 0,
//             'save_other_choice' => 0,
//             'default_value' => 'Black : black',
//             'layout' => 'horizontal',
//           ),
//           array (
//             'key' => 'field_5398b96eefdd1',
//             'label' => 'Slide Background Color',
//             'name' => 'slide_background_color',
//             'type' => 'color_picker',
//             'column_width' => '',
//             'default_value' => '#000000',
//           ),
//         ),
//         'row_min' => 1,
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Slide',
//       ),
//       array (
//         'key' => 'field_5398c91ea55b1',
//         'label' => 'Blurb Under Slider',
//         'name' => 'blurb_under_slider',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_5398cacfd90a2',
//         'label' => 'Call to Action Text',
//         'name' => 'call_to_action_text',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_5398cadfd90a3',
//         'label' => 'Call to Action Destination',
//         'name' => 'call_to_action_destination',
//         'type' => 'page_link',
//         'post_type' => array (
//           0 => 'all',
//         ),
//         'allow_null' => 0,
//         'multiple' => 0,
//       ),
//       array (
//         'key' => 'field_5398c9c5a55b2',
//         'label' => 'Sales Funnel Boxes',
//         'name' => 'sales_funnel_boxes',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_5398c9daa55b3',
//             'label' => 'Graphic',
//             'name' => 'graphic',
//             'type' => 'image',
//             'column_width' => '',
//             'save_format' => 'object',
//             'preview_size' => 'thumbnail',
//             'library' => 'all',
//           ),
//           array (
//             'key' => 'field_5398c9e8a55b4',
//             'label' => 'Title',
//             'name' => 'title',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_5398ca0ba55b7',
//             'label' => 'Content',
//             'name' => 'content',
//             'type' => 'wysiwyg',
//             'column_width' => '',
//             'default_value' => '',
//             'toolbar' => 'full',
//             'media_upload' => 'yes',
//           ),
//           array (
//             'key' => 'field_5398c9fca55b6',
//             'label' => 'Action Text',
//             'name' => 'action_text',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_5398ca1ba55b8',
//             'label' => 'Action Destination',
//             'name' => 'action_destination',
//             'type' => 'page_link',
//             'column_width' => '',
//             'post_type' => array (
//               0 => 'all',
//             ),
//             'allow_null' => 0,
//             'multiple' => 0,
//           ),
//           array (
//             'key' => 'field_5398ca41a55b9',
//             'label' => 'Display Newsletter Email Input?',
//             'name' => 'display_newsletter_email_input',
//             'type' => 'radio',
//             'column_width' => '',
//             'choices' => array (
//               'Yes' => 'Yes',
//               'No' => 'No',
//             ),
//             'other_choice' => 0,
//             'save_other_choice' => 0,
//             'default_value' => 'No',
//             'layout' => 'vertical',
//           ),
//         ),
//         'row_min' => 4,
//         'row_limit' => 4,
//         'layout' => 'row',
//         'button_label' => 'Add Row',
//       ),
//       array (
//         'key' => 'field_5398dcfcbc832',
//         'label' => 'Meet Scott Image',
//         'name' => 'meet_scott_image',
//         'type' => 'image',
//         'instructions' => 'Make sure that this image is at least 290px X 290px and is square.',
//         'save_format' => 'object',
//         'preview_size' => 'thumbnail',
//         'library' => 'all',
//       ),
//       array (
//         'key' => 'field_5398dd15bc833',
//         'label' => 'Meet Scott Content',
//         'name' => 'meet_scott_content',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_5398dd1fbc834',
//         'label' => 'Meet Scott CTA Text',
//         'name' => 'meet_scott_cta_text',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_5398dd2abc835',
//         'label' => 'Meet Scott CTA Destination',
//         'name' => 'meet_scott_cta_destination',
//         'type' => 'page_link',
//         'post_type' => array (
//           0 => 'all',
//         ),
//         'allow_null' => 0,
//         'multiple' => 0,
//       ),
//       array (
//         'key' => 'field_539f5bbe99ef4',
//         'label' => 'Happy Clients Text',
//         'name' => 'happy_clients_text',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_539f5bcb99ef5',
//         'label' => 'Happy Clients CTA Text',
//         'name' => 'happy_clients_cta_text',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_539f5bd699ef6',
//         'label' => 'Happy Clients CTA Destination',
//         'name' => 'happy_clients_cta_destination',
//         'type' => 'page_link',
//         'post_type' => array (
//           0 => 'all',
//         ),
//         'allow_null' => 0,
//         'multiple' => 0,
//       ),
//       array (
//         'key' => 'field_539f5be999ef7',
//         'label' => 'Happy Client Logos',
//         'name' => 'happy_client_logos',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_539f5bf799ef8',
//             'label' => 'Logo',
//             'name' => 'logo',
//             'type' => 'image',
//             'column_width' => '',
//             'save_format' => 'object',
//             'preview_size' => 'thumbnail',
//             'library' => 'all',
//           ),
//         ),
//         'row_min' => '',
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Logo',
//       ),
//       array (
//         'key' => 'field_539f5c0e99ef9',
//         'label' => 'Happy Client Logo Destination',
//         'name' => 'happy_client_logo_destination',
//         'type' => 'page_link',
//         'instructions' => 'This is the page you would like users to go to when they click on any of the client logos.',
//         'post_type' => array (
//           0 => 'all',
//         ),
//         'allow_null' => 0,
//         'multiple' => 0,
//       ),
//       array (
//         'key' => 'field_539f5c3399efa',
//         'label' => 'As Seen In Logos',
//         'name' => 'as_seen_in_logos',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_539f5c3c99efb',
//             'label' => 'Logo',
//             'name' => 'logo',
//             'type' => 'image',
//             'column_width' => '',
//             'save_format' => 'object',
//             'preview_size' => 'thumbnail',
//             'library' => 'all',
//           ),
//           array (
//             'key' => 'field_539f62129edcf',
//             'label' => 'Link Destination',
//             'name' => 'link_destination',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//         ),
//         'row_min' => '',
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Logo',
//       ),
//       array (
//         'key' => 'field_548dede8198f2',
//         'label' => 'Feedback Form',
//         'name' => 'feedback_form',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'tpl-home.php',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//         0 => 'the_content',
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_options-page-fields',
//     'title' => 'Options Page Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_5398905007df0',
//         'label' => 'Header Banner Text',
//         'name' => 'header_banner_text',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_539f7d430be1c',
//         'label' => 'Footer Middle Text',
//         'name' => 'footer_middle_text',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_539f7db10be1d',
//         'label' => 'Footer Last Text',
//         'name' => 'footer_last_text',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_5398e6e46cc9e',
//         'label' => 'Footer Banner Text',
//         'name' => 'footer_banner_text',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'options_page',
//           'operator' => '==',
//           'value' => 'acf-options',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_page-header-fields',
//     'title' => 'Page Header Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53a067908bf48',
//         'label' => 'Header Type',
//         'name' => 'header_type',
//         'type' => 'radio',
//         'instructions' => 'A primary level header has a bigger video on the right and a dark background.
//   A secondary level header has a smaller video on the left with a light background.',
//         'choices' => array (
//           'primary' => 'Primary Level Header',
//           'secondary' => 'Secondary Level Header',
//           'none' => 'No Header',
//         ),
//         'other_choice' => 0,
//         'save_other_choice' => 0,
//         'default_value' => 'primary',
//         'layout' => 'vertical',
//       ),
//       array (
//         'key' => 'field_53a0744fce7a3',
//         'label' => 'Header Image or Video?',
//         'name' => 'header_image_or_video',
//         'type' => 'radio',
//         'choices' => array (
//           'video' => 'Video',
//           'image' => 'Image',
//         ),
//         'other_choice' => 0,
//         'save_other_choice' => 0,
//         'default_value' => 'video',
//         'layout' => 'vertical',
//       ),
//       array (
//         'key' => 'field_53a068878bf49',
//         'label' => 'Header Video HTML',
//         'name' => 'header_video_html',
//         'type' => 'textarea',
//         'instructions' => 'To embed a video here: 1) Watch the video on YouTube 2) white the video is playing, right click the video 3) choose \'Get embed code\' 4) copy that code 5) Paste it here 6) change width to 500 and height to 305',
//         'conditional_logic' => array (
//           'status' => 1,
//           'rules' => array (
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '!=',
//               'value' => 'none',
//             ),
//             array (
//               'field' => 'field_53a0744fce7a3',
//               'operator' => '==',
//               'value' => 'video',
//             ),
//           ),
//           'allorany' => 'all',
//         ),
//         'default_value' => '',
//         'placeholder' => '',
//         'maxlength' => '',
//         'rows' => '',
//         'formatting' => 'html',
//       ),
//       array (
//         'key' => 'field_53a07472ce7a4',
//         'label' => 'Header Image',
//         'name' => 'header_image',
//         'type' => 'image',
//         'conditional_logic' => array (
//           'status' => 1,
//           'rules' => array (
//             array (
//               'field' => 'field_53a0744fce7a3',
//               'operator' => '==',
//               'value' => 'image',
//             ),
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '!=',
//               'value' => 'none',
//             ),
//           ),
//           'allorany' => 'all',
//         ),
//         'save_format' => 'object',
//         'preview_size' => 'thumbnail',
//         'library' => 'all',
//       ),
//       array (
//         'key' => 'field_53a06a288bf4a',
//         'label' => 'Header Title',
//         'name' => 'header_title',
//         'type' => 'text',
//         'conditional_logic' => array (
//           'status' => 1,
//           'rules' => array (
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '==',
//               'value' => 'primary',
//             ),
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '==',
//               'value' => 'secondary',
//             ),
//           ),
//           'allorany' => 'any',
//         ),
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_53a06a388bf4b',
//         'label' => 'Header Content',
//         'name' => 'header_content',
//         'type' => 'wysiwyg',
//         'conditional_logic' => array (
//           'status' => 1,
//           'rules' => array (
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '==',
//               'value' => 'primary',
//             ),
//             array (
//               'field' => 'field_53a067908bf48',
//               'operator' => '==',
//               'value' => 'secondary',
//             ),
//           ),
//           'allorany' => 'any',
//         ),
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'default',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'tpl-meet_the_team.php',
//           'order_no' => 0,
//           'group_no' => 1,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'acf_after_title',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//         0 => 'permalink',
//         1 => 'the_content',
//         2 => 'excerpt',
//         3 => 'custom_fields',
//         4 => 'discussion',
//         5 => 'comments',
//         6 => 'revisions',
//         7 => 'slug',
//         8 => 'author',
//         9 => 'format',
//         10 => 'featured_image',
//         11 => 'categories',
//         12 => 'tags',
//         13 => 'send-trackbacks',
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_recommended-reading-fields',
//     'title' => 'Recommended Reading Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53a0c00fe5111',
//         'label' => 'Featured Reading Image',
//         'name' => 'featured_reading_image',
//         'type' => 'image',
//         'save_format' => 'object',
//         'preview_size' => 'thumbnail',
//         'library' => 'all',
//       ),
//       array (
//         'key' => 'field_53a0c02de5112',
//         'label' => 'Featured Reading Title',
//         'name' => 'featured_reading_title',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_53a0c036e5113',
//         'label' => 'Featured Reading Author',
//         'name' => 'featured_reading_author',
//         'type' => 'text',
//         'default_value' => '',
//         'placeholder' => '',
//         'prepend' => '',
//         'append' => '',
//         'formatting' => 'html',
//         'maxlength' => '',
//       ),
//       array (
//         'key' => 'field_53a0c04ce5114',
//         'label' => 'Featured Reading Synopsis',
//         'name' => 'featured_reading_synopsis',
//         'type' => 'wysiwyg',
//         'default_value' => '',
//         'toolbar' => 'full',
//         'media_upload' => 'yes',
//       ),
//       array (
//         'key' => 'field_53a0c0ade5116',
//         'label' => 'Recomended Readings',
//         'name' => 'recomended_readings',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_53a0c0dbe5117',
//             'label' => 'Image',
//             'name' => 'image',
//             'type' => 'image',
//             'instructions' => 'Optional',
//             'column_width' => '',
//             'save_format' => 'object',
//             'preview_size' => 'thumbnail',
//             'library' => 'all',
//           ),
//           array (
//             'key' => 'field_53b4837d55187',
//             'label' => 'Image Link',
//             'name' => 'image_link',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53a0c100e5118',
//             'label' => 'Title',
//             'name' => 'title',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53a0c10ae5119',
//             'label' => 'Summary',
//             'name' => 'summary',
//             'type' => 'wysiwyg',
//             'column_width' => '',
//             'default_value' => '',
//             'toolbar' => 'full',
//             'media_upload' => 'yes',
//           ),
//           array (
//             'key' => 'field_53b47bf26188b',
//             'label' => 'Categories',
//             'name' => 'categories',
//             'type' => 'repeater',
//             'column_width' => '',
//             'sub_fields' => array (
//               array (
//                 'key' => 'field_53b47c026188c',
//                 'label' => 'Category',
//                 'name' => 'category',
//                 'type' => 'text',
//                 'column_width' => '',
//                 'default_value' => '',
//                 'placeholder' => '',
//                 'prepend' => '',
//                 'append' => '',
//                 'formatting' => 'html',
//                 'maxlength' => '',
//               ),
//             ),
//             'row_min' => '',
//             'row_limit' => '',
//             'layout' => 'row',
//             'button_label' => 'Add Category',
//           ),
//         ),
//         'row_min' => '',
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Row',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'tpl-recomended_reading.php',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'normal',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//         0 => 'permalink',
//         1 => 'the_content',
//         2 => 'excerpt',
//         3 => 'custom_fields',
//         4 => 'discussion',
//         5 => 'comments',
//         6 => 'revisions',
//         7 => 'slug',
//         8 => 'author',
//         9 => 'format',
//         10 => 'featured_image',
//         11 => 'categories',
//         12 => 'tags',
//         13 => 'send-trackbacks',
//       ),
//     ),
//     'menu_order' => 0,
//   ));
//   register_field_group(array (
//     'id' => 'acf_meet-the-team-fields',
//     'title' => 'Meet the Team Fields',
//     'fields' => array (
//       array (
//         'key' => 'field_53b5b91f72da6',
//         'label' => 'Team Members',
//         'name' => 'team_members',
//         'type' => 'repeater',
//         'sub_fields' => array (
//           array (
//             'key' => 'field_548ddf772dee4',
//             'label' => 'Headshot',
//             'name' => 'headshot',
//             'type' => 'image_crop',
//             'column_width' => '',
//             'crop_type' => 'hard',
//             'target_size' => 'custom',
//             'width' => 280,
//             'height' => 280,
//             'preview_size' => 'thumbnail',
//             'force_crop' => 'no',
//             'save_in_media_library' => 'yes',
//             'retina_mode' => 'no',
//             'save_format' => 'object',
//           ),
//           array (
//             'key' => 'field_53b5b96172da9',
//             'label' => 'Name',
//             'name' => 'name',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53b5b96772daa',
//             'label' => 'Title',
//             'name' => 'title',
//             'type' => 'text',
//             'column_width' => '',
//             'default_value' => '',
//             'placeholder' => '',
//             'prepend' => '',
//             'append' => '',
//             'formatting' => 'html',
//             'maxlength' => '',
//           ),
//           array (
//             'key' => 'field_53b5b97172dab',
//             'label' => 'Description',
//             'name' => 'description',
//             'type' => 'wysiwyg',
//             'column_width' => '',
//             'default_value' => '',
//             'toolbar' => 'full',
//             'media_upload' => 'yes',
//           ),
//         ),
//         'row_min' => '',
//         'row_limit' => '',
//         'layout' => 'row',
//         'button_label' => 'Add Team Member',
//       ),
//     ),
//     'location' => array (
//       array (
//         array (
//           'param' => 'page_template',
//           'operator' => '==',
//           'value' => 'tpl-meet_the_team.php',
//           'order_no' => 0,
//           'group_no' => 0,
//         ),
//       ),
//     ),
//     'options' => array (
//       'position' => 'acf_after_title',
//       'layout' => 'no_box',
//       'hide_on_screen' => array (
//       ),
//     ),
//     'menu_order' => 10,
//   ));
// }

?>